---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment-rolling
  labels:
    app: maven-web-dep
  namespace: mynamespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maven-web-dep
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: maven-web-dep
    spec:
      containers:
        - name: maven-web-application
          image: hemanth9774/maven-web-application:REPLACE_TAG
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: mynamespace
spec:
  type: NodePort
  selector:
    app: maven-web-dep
  ports:
    - port: 80
      targetPort: 8080
